(load-library "package")
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages"))
(add-to-list 'package-archives '("marmalade" . "https://marmalade-repo.org/packages/"))
(setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
(package-refresh-contents)
(dolist (p '("dash" "dash-functional" "ht" "org-ql" "org-super-agenda" "ov" "peg" "s" "ts"))
  (package-install p))
